export default function PDFFooter() {

  return (
    <div
      style={{
        marginTop: 70,
        borderTop: "1px solid #e2e8f0",
        paddingTop: 24,
        color: "#64748b",
        fontSize: 13,
      }}
    >
      Generated by Credex AI • Confidential Optimization Report
    </div>
  );
}